一覧表示関連のUI実装
team-azb/knowtfolio pull request #135
Opened 2022-10-31 15:13 UTC by reibomaru

- アカウントページでの`article collection`
- `/search`での記事検索画面UI

2022-11-21 13:02 UTC, reibomaru commented
- `wallet address display`に未認証の場合の表示を追加する
- `defaultLoadingDisplay`関連の表示を削除する

2022-11-28 09:09 UTC, shugo256 requested changes
お待たせ

2022-11-28 09:09 UTC, shugo256 commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +        <WalletAddressDisplay address={props.article.owner_address} />
この後半部以外OwnedArticleCardと全く一緒なので共通化した方が良さそう

2022-11-28 09:09 UTC, shugo256 commented on client/src/components/atoms/search/Input/index.tsx
> +const Input = (
そして IMO: search専用ならぶっちゃけ切り出す必要性をあまり感じない（使う場所一箇所なので）

2022-11-28 09:09 UTC, shugo256 commented on client/src/components/atoms/search/Input/index.tsx
> +const Input = (
あとドキュメント抜けてる

2022-11-28 09:09 UTC, shugo256 commented on client/src/components/pages/AccountPage/index.tsx
> +          <OwnedArticleTable />
これはスッキリしていいリファクタ（別のPRに分けて欲しかったが）

2022-11-29 09:57 UTC, reibomaru commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +          <TrancatedText str={props.article.title} m={25} n={5} />
https://qiita.com/Luke02561/items/74995d9d5f0e20cbf2a0
こういう感じで「〇〇〇〇 partX」みたいにシリーズ物の記事書く人いそうだなと思いあえての後ろ少し見せるようにしていたけど、どう？

2022-11-29 10:25 UTC, shugo256 commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +          <TrancatedText str={props.article.title} m={25} n={5} />
そもそもタイトルの文字数制限50とかに設定して、省略させない説ない？

2022-11-29 10:28 UTC, shugo256 commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +          <TrancatedText str={props.article.title} m={25} n={5} />
zennはこんな感じ
<img width="909" alt="スクリーンショット 2022-11-29 19 23 27" src="https://user-images.githubusercontent.com/35961216/204504829-c85f1b33-3016-43b9-8fdf-a390d539ec46.png">
一個三行になってはみ出し気味のやついるけど、ちょっと間隔変えるだけでカモフラージュしてる

2022-11-30 03:47 UTC, reibomaru commented on client/src/components/pages/AccountPage/index.tsx
> +          <OwnedArticleTable />
すまぬぅ。。

2022-11-30 03:48 UTC, reibomaru commented on client/src/App.tsx
> +          <Route path="/search" element={<SearchPage />} />
03ca9de で対応した

2022-11-30 03:49 UTC, reibomaru commented on client/src/components/atoms/TruncatedText/index.tsx
> +  str: string;
b857254 で対応した

2022-11-30 03:49 UTC, reibomaru commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +        <WalletAddressDisplay address={props.article.owner_address} />
daefe0b で共通化した

2022-11-30 03:54 UTC, reibomaru commented on client/src/components/atoms/search/Input/index.tsx
> +const Input = (
現時点で再利用しないので d44eea0 でコンポーネントで切り出さないようにした

2022-11-30 03:57 UTC, reibomaru commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +          <TrancatedText str={props.article.title} m={25} n={5} />
> そもそもタイトルの文字数制限50とかに設定して、省略させない説ない？

これがいいと思う。日本語と英語で文字数違い出てくるけど、そこもうまいこと対応したさある。いずれにしてもIssueで対応かな

2022-11-30 05:35 UTC, reibomaru commented on client/src/components/organisms/tables/SearchResultTable/index.tsx
> +    </Grid>
わすれとった。 c860d4c でページング実装した

2022-11-30 06:52 UTC, shugo256 commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +          <TrancatedText str={props.article.title} m={25} n={5} />
であればissue立ててもらえると

2022-11-30 06:53 UTC, shugo256 commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +          <TrancatedText str={props.article.title} m={25} n={5} />
てか50文字でも行数の違いは出てきそうだけどそこは大丈夫なん？

2022-11-30 06:53 UTC, shugo256 reviewed
検索結果のタイトルのとこだけ

2022-11-30 07:13 UTC, reibomaru commented on client/src/components/organisms/cards/SearchedArticleCard/index.tsx
> +          <TrancatedText str={props.article.title} m={25} n={5} />
#177 作った。
> てか50文字でも行数の違いは出てきそうだけどそこは大丈夫なん？ 

これは、zennのUIを見た感じflexboxというCSSのレイアウトのパターンを使えば行けそう。折返したタイトルの高さと、画像の高さのうち、高い方に合わせてカードの高さを決めるようなイメージ

2022-11-30 07:17 UTC, shugo256 reviewed
すまぬ、あと一点あった

2022-11-30 07:17 UTC, shugo256 commented on client/src/components/organisms/tables/OwnedArticleTable/index.tsx
> +const pageSize = 12;
これ固定でいいの？画面サイズとかにもよりそうだけど

2022-11-30 07:39 UTC, reibomaru commented on client/src/components/organisms/tables/OwnedArticleTable/index.tsx
> +const pageSize = 12;
レスポンシブ対応のときにまとめてやろうと思う。#143 に追加してある。

2022-11-30 09:47 UTC, shugo256 approved these changes
LGTM

2022-11-30 14:45 UTC, merged