code deploy + github actionsでデプロイの自動化
team-azb/knowtfolio pull request #183
Opened 2022-12-05 06:27 UTC by reibomaru

#169 の続き
close #156 

#169 でcode deployを使って手動で実行するところまでは成功していたので、これを`appspec.yml` `github actions`をつかって自動化した。
github actions(`Server deploy`)の構成
- prductブランチの`Server test`が実行終了したら`Server deploy`がトリガーされる
- build job
  - `Server test`が成功していたら実行、成功していなかったらスキップ
  - buildして、バイナリと`.env`を`actions/upload-artifact@v3`でアップロード
- deploy job
  - アップロードされたバイナリや`.env`を`infrastructure/deploy/server`に加えてこれられをまとめて`zip`にしてs3にアップロード
  - s3にアップロードされたファイルを使ってcode deployの`create deployment`コマンドをトリガーしてデプロイを開始させる

TODO
- #166 
- #182

2022-12-06 07:02 UTC, shugo256 requested changes

2022-12-06 07:02 UTC, shugo256 commented on infrastructure/deploy/server/scripts/startApp.sh
> +export $(cat $APP_ROOT/.env | grep -v '^#' | xargs)
これは何をしている？

2022-12-06 07:02 UTC, shugo256 commented on infrastructure/deploy/server/scripts/startApp.sh
> +nohup $APP_ROOT/server > $APP_ROOT/knowtfolio.out.log 2> $APP_ROOT/knowtfolio.err.log < /dev/null &
この`/dev/null`は何のために入れているん？

2022-12-17 07:14 UTC, reibomaru commented on infrastructure/deploy/server/scripts/startApp.sh
> +export $(cat $APP_ROOT/.env | grep -v '^#' | xargs)
これは説明したかもだけど、`.env`の`#`をつかったコメントアウト以外の行をexportしている

2022-12-17 07:28 UTC, reibomaru commented on .github/workflows/server-deploy.yml
> +    branches: [product]
[5b503d7](https://github.com/team-azb/knowtfolio/pull/183/commits/5b503d75f44f4bc8d7ab8b4af517a90a03dcc787)で`main`にした

2022-12-17 07:29 UTC, reibomaru commented on .github/workflows/server-deploy.yml
> +      - name: setup-dotenv
[5b503d7](https://github.com/team-azb/knowtfolio/pull/183/commits/5b503d75f44f4bc8d7ab8b4af517a90a03dcc787)で修正した

2022-12-17 07:30 UTC, reibomaru commented on infrastructure/deploy/server/scripts/setUp.sh
> +chmod 755 /home/ubuntu/knowtfolio/server
28a223a で修正した

2022-12-17 07:30 UTC, reibomaru commented on .github/workflows/server-deploy.yml
> +name: Server deploy
[5b503d7](https://github.com/team-azb/knowtfolio/pull/183/commits/5b503d75f44f4bc8d7ab8b4af517a90a03dcc787)で修正した

2022-12-17 07:33 UTC, reibomaru commented on infrastructure/deploy/server/scripts/stopApp.sh
> +  kill -9 $PID
[ac6c86f](https://github.com/team-azb/knowtfolio/pull/183/commits/ac6c86fdd4a6fc581d4e4e08832adc3ec20c26e6)で修正した

2022-12-17 07:34 UTC, reibomaru commented on infrastructure/deploy/server/scripts/stopApp.sh
> +  echo "kill server PID:$PID"
[ac6c86f](https://github.com/team-azb/knowtfolio/pull/183/commits/ac6c86fdd4a6fc581d4e4e08832adc3ec20c26e6)で`stopped`に修正

2022-12-17 07:34 UTC, reibomaru commented on Makefile
> +	docker-compose run server go build
[5e80b15](https://github.com/team-azb/knowtfolio/pull/183/commits/5e80b15b0b2a0298c993a318e7f3499d3a0d7a95)で対応

2022-12-17 14:58 UTC, reibomaru commented on infrastructure/deploy/server/scripts/startApp.sh
> +nohup $APP_ROOT/server > $APP_ROOT/knowtfolio.out.log 2> $APP_ROOT/knowtfolio.err.log < /dev/null &
`/dev/null`はここに書き込まれるとすべて破棄されるファイルらしい。
なので`< /dev/null`は標準入力に何も指定しないことを指示しているのだが、丁寧にこれ指定しなくてもいい説あるので試してみる
https://explainshell.com/explain?cmd=nohup+bash+-c+run_forever+%3C%2Fdev%2Fnull+%3E%2Fdev%2Fnull+2%3E%261+%26#

2022-12-18 08:45 UTC, reibomaru commented on Makefile
> +	docker-compose run server go build
Makefileで宣言している環境変数をexportしないとだめなので、コマンド直書きだと環境変数がないので、ビルドが通らなくなる。Makefileで実行する必要がありそう。
[8569e14](https://github.com/team-azb/knowtfolio/pull/183/commits/8569e145020116245c5a82a252ff507920d67e9a)で一旦戻した。

2022-12-18 08:55 UTC, reibomaru commented on infrastructure/deploy/server/scripts/startApp.sh
> +nohup $APP_ROOT/server > $APP_ROOT/knowtfolio.out.log 2> $APP_ROOT/knowtfolio.err.log < /dev/null &
なくても動作するので、消した。([93e738e](https://github.com/team-azb/knowtfolio/pull/183/commits/93e738e09bb653b8104165c425b4aa6a3e377ec5))

2022-12-19 15:12 UTC, reibomaru commented on Makefile
> +	docker-compose run server go build
[71bb653](https://github.com/team-azb/knowtfolio/pull/183/commits/71bb65326b78a25ad4731b92e6350968babaa1ff)で`make server/build/server`みたくバイナリファイルを直接Makefileのターゲットに指定する書き方にした

2022-12-21 09:16 UTC, shugo256 requested changes
細かい点だけ

2022-12-21 09:16 UTC, shugo256 commented on Makefile
> +server/build/server: $(GOA_GEN_DIR) $(GO_ETH_BINDING_PATH)
これはPHONYではなく実ファイルなので、上の方（59行目より上）に移動してほしい

2022-12-21 09:16 UTC, shugo256 commented on server/build/.gitignore
> +server
NITS: 末尾改行

2022-12-21 10:05 UTC, reibomaru commented on server/build/.gitignore
> +server
0a39a82 で対応した

2022-12-21 10:05 UTC, reibomaru commented on Makefile
> +server/build/server: $(GOA_GEN_DIR) $(GO_ETH_BINDING_PATH)
8354358 で対応した

2022-12-27 09:12 UTC, shugo256 approved these changes
お待たせLGTM

2022-12-27 09:19 UTC, merged