SSRの実装
team-azb/knowtfolio pull request #195
Opened 2022-12-16 08:54 UTC by reibomaru

2022-12-17 06:57 UTC, reibomaru commented on client/tsconfig.json
> +        "webpack.config.js",
今回の修正の内容とは別のリファクタにあたるけど、一行だったので。。
【リファクタ内容】
excludeでtypescriptの型チェックを除外するファイルを指定でき、webpack.config.jsは型チェックから除外するべきなのだが、それが抜けていたので追加した。

2022-12-17 07:06 UTC, reibomaru commented on server/models/article_test.go
> +	assert.NoError(t, err)
相対パスを使っている箇所があるために、ディレクリを移動する処理をはじめにする必要があるのだが、これをこの箇所で実行するのが適切なのかよくわからなかったので相談したい。（そもそも、相対パスを使うべきか絶対パスにすべきかもふくめて。）

2022-12-19 15:13 UTC, reibomaru commented on server/models/article_test.go
> +	assert.NoError(t, err)
ファイルのパス指定をglobal変数を使って書き換えてテストと本番実行で切り替えるようにする

2022-12-21 06:23 UTC, reibomaru commented on server/models/article_test.go
> +	assert.NoError(t, err)
[e82a991](https://github.com/team-azb/knowtfolio/pull/195/commits/e82a99174a1aab4a03febd44c5a2798a7a264f17)で対応した

2022-12-21 10:52 UTC, shugo256 requested changes
これ結構複雑なことしてると思うから、後から見返した時に死なないようになるべく曖昧さは排除していきたい。

2022-12-21 10:52 UTC, shugo256 commented on server/models/article_test.go
> +	TemplateDir = root + "/static"
NITS of NITS: この下1行開けたい（段落分け的な）

2022-12-21 10:52 UTC, shugo256 commented on server/models/article.go
> +	TemplateDir       = filepath.Dir(ExecutablePath) + "/static"
これは`+`ではなく`filepath.Join`でお願いしたい

2022-12-21 10:52 UTC, shugo256 commented on server/models/article.go
> +	TemplateDir       = filepath.Dir(ExecutablePath) + "/static"
あとTemplateDirじゃなくてTemplatePathでよさそう

2022-12-21 10:52 UTC, shugo256 commented on server/models/article_test.go
> +	expected := `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link
これmetamaskに接続してくださいは結局直してないん？

2022-12-21 10:52 UTC, shugo256 commented on server/static/.gitignore
> +*.html
NITS: 末尾改行

2022-12-21 10:52 UTC, shugo256 commented on docker-compose.yml
> -      - server
これ外さなくても、`docker compose run`を呼ぶときだけ`--no-deps`オプションをつければいけるはず

https://docs.docker.jp/compose/reference/run.html#:~:text=uid%20%E3%82%92%E6%8C%87%E5%AE%9A-,%2D%2Dno%2Ddeps,-%E3%83%AA%E3%83%B3%E3%82%AF%E3%81%97%E3%81%9F%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9

2022-12-21 10:52 UTC, shugo256 commented on Makefile
> +		/bin/bash -c "npm run build && node dist/createArticleTemplate.js"
IMO: 
```
docker-compose run client npm run build
docker-compose run client node dist/createArticleTemplate.js
```
でよさそう

2022-12-21 10:52 UTC, shugo256 commented on Makefile
> +	cp -f $(CLIENT_DIST_DIR)/template.html ./server/static
このコピーは`mv`ではダメなん？

2022-12-21 10:52 UTC, shugo256 commented on Makefile
> +	cp -f $(CLIENT_DIST_DIR)/template.html ./server/static
そして`$(ARTICLE_PAGE_TEMPLATE)`を変数にしたのだから、コピーするなら
```
cp -f $(CLIENT_DIST_DIR)/template.html $(ARTICLE_PAGE_TEMPLATE)
```
とした方が良さそう

2022-12-21 10:52 UTC, shugo256 commented on Makefile
> +	cp -f $(CLIENT_DIST_DIR)/template.html ./server/static
さらに、もしコピーするならこのターゲットでは`$(ARTICLE_PAGE_TEMPLATE)`だけではなく`$(CLIENT_DIST_DIR)/template.html`も生成されているから、これも追加するべき

2022-12-21 10:52 UTC, shugo256 commented on Makefile
> +	cp -f $(CLIENT_DIST_DIR)/template.html ./server/static
さらにさらに、もしコピーするなら、このターゲットの依存である`$(CLIENT_SRCS)`の中に生成物である`$(CLIENT_DIST_DIR)/template.html`が含まれてしまっているから、変更がなくても毎回実行されそう

2022-12-21 10:52 UTC, shugo256 commented on client/src/csr.tsx
>  import App from "./App";
ファイル名略さずにserver-side renderingとclient-side renderingを明確にしちゃった方がいいと思う

2022-12-21 10:52 UTC, shugo256 commented on client/src/createArticleTemplate.tsx
> + * 記事画面のssrのためにgoで用いられるhtmlのテンプレートを作成する関数
ssr -> Server-Side Rendering
go -> backend

2022-12-21 10:52 UTC, shugo256 commented on client/src/createArticleTemplate.tsx
> +  const fileBuf = await fs.readFile(`${__dirname}/_template.html`);
このファイルが何者なのかよくわからないんだけど、`_template`の部分もう少しわかりやすいものに変えられたりしない？

2022-12-21 10:52 UTC, shugo256 commented on Makefile
> +ARTICLE_PAGE_TEMPLATE = server/static/template.html
`article_template.html`の方が良さそう

2022-12-21 10:52 UTC, shugo256 commented on client/types/index.d.ts
> +declare const __isBrowser__: boolean
IMO: より明確に
```JavaScript
__RenderOn__: "ClientSide" | "ServerSide"
```
みたいにできたりしない？

2022-12-21 10:52 UTC, shugo256 commented on client/webpack.config.js
> +  {
これエントリごとに軽くコメントが欲しいかも

2022-12-21 10:52 UTC, shugo256 commented on client/src/createArticleTemplate.tsx
> +      <App />
そもそも、webpack.config.jsで`__isBrowser__`みたいなグローバルの値設定せずに、`App`のpropsで行けたりはしないの？

2022-12-27 02:32 UTC, reibomaru commented on server/static/.gitignore
> +*.html
0916066 で対応した

2022-12-27 02:33 UTC, reibomaru commented on server/models/article_test.go
> +	expected := `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link
#119 は別ブランチで作業する予定（ファイルの差分結構な数になりそうなので）

2022-12-27 03:09 UTC, reibomaru commented on client/src/createArticleTemplate.tsx
> +      <App />
できないことはないけど、propsをコンポーネント経由で一つづつ受け渡していかなくてはいけないので、各コンポーネントにこの値のためのpropsが増えてしまう。なのでグローバルにしたほうがいい気がする。

2022-12-27 04:31 UTC, reibomaru commented on client/webpack.config.js
> +  {
7b974f3 で追加

2022-12-27 04:31 UTC, reibomaru commented on Makefile
> +ARTICLE_PAGE_TEMPLATE = server/static/template.html
9e16294 で対応

2022-12-27 04:47 UTC, reibomaru commented on client/src/createArticleTemplate.tsx
> +  const fileBuf = await fs.readFile(`${__dirname}/_template.html`);
9e16294 で対応
`_template.html`は`<App/>`がレンダーされていない状態の`template.html`を指していた。

修正前
1. webpackで`_template.html`が作成
2. `createArticleTemplate.js`で`_template.html`から`template.html`を作成

修正点
- `template.html`を`article_template.html`にrename
- `createArticleTemplate.js`を`<App/>`を挿入してhtmlを新規作成する仕様から、上書きする仕様に変更し、ファイル名も`createArticleTemplate`から`insertPageContent`にした。それにともなって、`_template.html`が消滅。

修正後
1. webpackで`article_template.html`が作成
2. `insertPageContent.js`で`article_template.html`に<App/>が挿入される

2022-12-27 04:48 UTC, reibomaru commented on server/models/article.go
> +	TemplateDir       = filepath.Dir(ExecutablePath) + "/static"
9e16294 で対応した

2022-12-27 04:48 UTC, reibomaru commented on server/models/article_test.go
> +	TemplateDir = root + "/static"
9e16294 で対応した

2022-12-27 04:49 UTC, reibomaru commented on client/src/csr.tsx
>  import App from "./App";
9e16294 で対応した

2022-12-27 04:49 UTC, reibomaru commented on client/src/createArticleTemplate.tsx
> + * 記事画面のssrのためにgoで用いられるhtmlのテンプレートを作成する関数
9e16294 で対応した

2022-12-27 04:51 UTC, reibomaru commented on Makefile
> +	cp -f $(CLIENT_DIST_DIR)/template.html ./server/static
1bf9223 で対応
- `mv`に変更
- 環境変数使う表現に
- ファイル名変更関連

2022-12-27 04:51 UTC, reibomaru commented on Makefile
> +		/bin/bash -c "npm run build && node dist/createArticleTemplate.js"
1bf9223 で対応

2022-12-27 05:51 UTC, reibomaru commented on .github/actions/setup-dotenv-cl/action.yml
> +name: setup-dotenv-cl
6746db7 で対応

2022-12-27 07:37 UTC, reibomaru commented on docker-compose.yml
> -      - server
975531c で`--no-deps`オプションで実装し直した

2022-12-27 07:38 UTC, reibomaru commented on client/types/index.d.ts
> +declare const __isBrowser__: boolean
f22464f で対応した。

2022-12-27 09:14 UTC, shugo256 commented on server/models/article.go
> +	TemplateDir       = filepath.Dir(ExecutablePath) + "/static"
> TemplatePathでよさそう

の意図は、`article_template.html`まで変数に入れてよさそうという意味だった、すまぬ

2022-12-27 09:18 UTC, shugo256 commented on client/types/index.d.ts
> +declare const __isBrowser__: boolean
ナイス共通化

2022-12-27 09:18 UTC, shugo256 commented on client/src/createArticleTemplate.tsx
> +      <App />
なるほどね、理解した

2022-12-27 09:19 UTC, shugo256 requested changes
パス変数のところだけ

2022-12-27 09:34 UTC, reibomaru commented on server/models/article.go
> +	TemplateDir       = filepath.Dir(ExecutablePath) + "/static"
なるほどな。 1fa923e で対応した。

2022-12-27 09:37 UTC, reibomaru commented on server/models/article.go
> +	TemplateDir       = filepath.Dir(ExecutablePath) + "/static"
9e16294 の変更で共有し忘れていたことがあったので共有

もともとは、`os.Executable()`でバイナリのファイルパスを取得していたんだけど、これだと、`go run main.go`のときに実行用に一時的に作成されるバイナリのパスが入ってきてしまうので、`os.Getwd()`で実行時のワーキングディレクトリを使うように変更した。
↑の変更でグルーバル変数名も変えるべきだったのだけど、それを忘れていたので 1fa923e で変数名も変更した。

2022-12-27 09:42 UTC, reibomaru commented
code-deploy用の設定を追加するの忘れていたので、その作業追加します。

2022-12-27 10:09 UTC, shugo256 approved these changes
LGTM

2023-01-06 09:13 UTC, reibomaru commented on .github/workflows/server-deploy.yml
> +          path: infrastructure/deploy/server
ここはmainとのコンフリクトを修正するときのミスをリカバーしたものなので見なくてもおけです。（コミット分けるのを怠たった :bow: ）

2023-01-06 09:15 UTC, reibomaru commented
@shugo256  
code-deployを実行するためのセッティングを 65c33aa で追加した。
- react-toastifyのcssをビルドするために設定を変更しなければならない箇所があったので対応
- `article_template.html`のパスを合わせるために、code-deployでworkingディレクトリを変更する必要が出てきたので変更

2023-01-06 09:28 UTC, shugo256 commented on .github/workflows/server-deploy.yml
> +          path: infrastructure/deploy/server
ん、これ`article_template.html`が`server`に変わっているのはなぜ？

2023-01-06 09:33 UTC, reibomaru commented on .github/workflows/server-deploy.yml
> +          path: infrastructure/deploy/server
serverはファイル名ではなく、ディレクトリを指している。infrastrutture/deploy/server/にデプロイするファイルを全部集めてzipで固めてs3におく仕様になってる。
(article_template.htmlが指定されていたのはコンフリクト直した時のそもそものミス)

2023-01-06 10:09 UTC, shugo256 approved these changes
LGTM2

2023-01-06 10:11 UTC, merged