dynamodbでのアドレス管理をについてclientを対応
team-azb/knowtfolio pull request #212
Opened 2023-01-07 01:58 UTC by reibomaru

2023-01-09 13:42 UTC, reibomaru commented
- wallet_address登録用のsignDataを書き換える
- post confirmationでcognitoのcustom:wallet_addressをmetadataに書き換え

2023-01-20 08:03 UTC, shugo256 requested changes
お待たせ
いくつかコメント

2023-01-20 08:03 UTC, shugo256 commented on client/src/components/organisms/forms/SignUpForm/index.tsx
> +        // TODO: サインインして/wallet-registerへ遷移させる
これ今回はやらんの？

2023-01-20 08:03 UTC, shugo256 commented on client/src/components/organisms/providers/AuthProvider/index.tsx
> +        // TODO: toastでUIを整える
これも今回はやらん感じ？

2023-01-23 07:15 UTC, reibomaru commented on infrastructure/iam.tf
> +resource "aws_iam_role_policy" "get_item_from_dynamodb" {
このリソースはロールとポリシーを紐付けるものだからどこからも参照されない、で大丈夫

2023-01-23 07:56 UTC, reibomaru commented on client/src/components/organisms/forms/SignUpForm/index.tsx
> +        // TODO: サインインして/wallet-registerへ遷移させる
ここの実装は #181 に依存していて`move-wallet-info-to-dynamodb`ブランチにはこのPRは反映されていないので、`move-wallet-info-to-dynamodb`がmainにマージされた後に、mainからブランチを切って作業する予定にした(#225)。

2023-01-23 07:57 UTC, reibomaru commented on client/src/components/organisms/providers/AuthProvider/index.tsx
> +        // TODO: toastでUIを整える
こっちも、#225 で対応

2023-01-23 08:12 UTC, reibomaru commented on infrastructure/function_scripts/pkg/models/sign_up_form.go
> -			},
[b3d1c69](https://github.com/team-azb/knowtfolio/pull/212/commits/b3d1c69440ab5cf922813df9623027e38c873db0)で対応した。この箇所に関連してほかも削除しているので確認してもらえると（ビルドは通っている）

2023-01-23 08:12 UTC, reibomaru commented on infrastructure/iam.tf
> +// TODO: 他のpolicyもこの記法で統一する
de33b54 で削除

2023-01-23 08:14 UTC, reibomaru commented on client/src/apis/cognito.ts
> +type metaData = {
c285c3b このtypeとそれに対応する変数は一箇所だけでしか使っていないので、型定義自体削除してしまった。

2023-01-23 08:15 UTC, reibomaru commented on client/src/apis/dynamodb.ts
> + * @param jwtToken ログイン済みユーザーのjwtトークン
8a128f1 で`idToken`に統一

2023-01-23 08:15 UTC, reibomaru commented on client/src/apis/dynamodb.ts
> +export const initDynamodbClientWithJwtToken = (jwtToken: string) => {
8a128f1 で対応

2023-01-23 08:16 UTC, reibomaru commented on client/src/components/organisms/forms/RegisterWalletForm/index.tsx
> +const MessageToRejectRegistration = () => {
Chat GPTで提案ナイスだな。`RegisteredWalletAddressMessage`を採用させていただきました。 de579af

2023-01-23 08:17 UTC, reibomaru commented on client/src/components/organisms/forms/RegisterWalletForm/index.tsx
> +        <Grid container direction="column" spacing={3}>
aa8a62e で修正

2023-01-23 08:28 UTC, shugo256 commented on infrastructure/function_scripts/pkg/models/sign_up_form.go
> -			},
見た感じ大丈夫そう&ビルド通ってるならヨシ！

2023-01-23 08:28 UTC, shugo256 commented on infrastructure/iam.tf
> +resource "aws_iam_role_policy" "get_item_from_dynamodb" {
なるほど確かに

2023-01-23 08:31 UTC, shugo256 approved these changes
LGTM

2023-01-23 09:33 UTC, merged