他ユーザーの公開アカウント情報を取得できるように
team-azb/knowtfolio pull request #240
Opened 2023-02-11 03:01 UTC by reibomaru

closes #226 

他のユーザーのアカウント情報を見れるようにする必要があるのでlambdaで一部のアカウント情報を認証無しで取得することができるエンドポイントを作成した。

公開されるアカウント情報は以下
- ユーザー名
- アイコンurl
- 自己紹介文
- website情報
- wallet address

フロントではアカウント情報のエンドポイントを`/mypage` -> `/users/userId`に変更し、自分の`userId`のページを開いたときのみアカウント情報の編集ができる仕様に変更した。

2023-02-16 06:31 UTC, shugo256 requested changes

2023-02-16 06:31 UTC, shugo256 commented on client/src/apis/knowtfolio.ts
> +  owner_address: string;
これaddressの方はswaggerでの定義の通りrequiredではないので、nullになりうる

2023-02-16 06:31 UTC, shugo256 commented on client/src/apis/lambda.ts
> +export type PublicUserInfo = {
普通に`UserInfo`でいい気がした

2023-02-16 06:31 UTC, shugo256 commented on client/src/apis/lambda.ts
> +  website: string;
`website`, `picture`共に実体があいまい（特に`picture`）なので、`_url`つけたい

2023-02-16 06:31 UTC, shugo256 commented on infrastructure/function_scripts/pkg/models/public_user_info.go
> +}
ここも`UserInfo`でいいし、`Website`と`Picture`の命名直したい

2023-02-16 06:31 UTC, shugo256 commented on client/src/apis/lambda.ts
> +  biography: string;
picture ~ biographyまではnullableではないん？

2023-02-16 12:38 UTC, reibomaru commented on client/src/apis/lambda.ts
> +  biography: string;
値が未設定の場合は空文字を返すようにしているので、nullableにはしてない

2023-02-16 12:39 UTC, reibomaru commented on client/src/apis/knowtfolio.ts
> +  owner_address: string;
5a0c837 で対応した

2023-02-16 12:39 UTC, reibomaru commented on infrastructure/function_scripts/cmd/get_user/main.go
> +	jsonBody, _ := json.Marshal(userInfo)
aba8810 でエラー処理追加した

2023-02-16 12:39 UTC, reibomaru commented on infrastructure/function_scripts/cmd/get_user/main.go
> +	// `wallet_address` should exist after passing the `define` phase.
d590034 で修正した。

2023-02-16 13:42 UTC, reibomaru commented on infrastructure/function_scripts/pkg/models/public_user_info.go
> +}
e0ec672 で対応した

2023-02-16 13:42 UTC, reibomaru commented on client/src/apis/lambda.ts
> +  website: string;
e0ec672 で対応した

2023-02-16 13:42 UTC, reibomaru commented on client/src/apis/lambda.ts
> +export type PublicUserInfo = {
e0ec672 で対応した

2023-02-16 13:44 UTC, reibomaru commented on infrastructure/function_scripts/cmd/get_user/main.go
> +	username := path.Base(request.RawPath)
`/`を入れられるとフロントのルーティングも対応できなくなるので、#234 で`/`入れられないようにするのが良さそう

2023-02-19 07:22 UTC, shugo256 approved these changes

2023-02-20 11:35 UTC, merged