nftのメタデータ作成用のawsリソース作成
team-azb/knowtfolio pull request #63
Opened 2022-07-13 07:43 UTC by reibomaru

以下のリソースを用意した
- `knowtfolio-alpha`というs3 bucket
  - cloudfrontからgetが出来るという設定もついている（この点はknowtfolioという名前のs3 bucketと同じ仕様）
- ↑のbucketの`/nfts/`階層のCRUDを行う権限を持つiam user

2022-07-13 08:55 UTC, shugo256 approved these changes
LGTM

2022-07-13 09:00 UTC, shugo256 requested changes
と思ったけど、dev用のバケットも作った方がいい説ない？

2022-07-13 09:07 UTC, shugo256 approved these changes

2022-07-13 09:15 UTC, shugo256 commented
> ただ、現時点でprd環境使わなさそうだから、

これはalpha版公開時には作るということよね？

2022-07-13 09:18 UTC, reibomaru commented
Yes  
prd環境をつくる、というpr作る方がレビューもしやすいかなと思ったという意図もある

2022-07-14 02:04 UTC, reibomaru commented
@shugo256  
フロント用のs3 bucket -> `dev-knowtoflio`
その他で使うs3 bucket -> `dev-knowtfolio-resources  
というバケット名に変更しました

2022-07-14 02:04 UTC, merged